sudo: required
services:
  - docker
  
before_install:
  - docker build -t jmfrippiatsword/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true jmfrippiatsword/docker-react npm run test